"""empty message

Revision ID: 7774971a5c64
Revises: eafb5f79f888
Create Date: 2024-02-02 14:48:24.344185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7774971a5c64'
down_revision = 'eafb5f79f888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle')
    with op.batch_alter_table('favorit', schema=None) as batch_op:
        batch_op.drop_constraint('favorit_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_column('vehicle_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('favorit_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    op.create_table('vehicle',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('consumables', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('manufacturer', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('passengers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cargo_capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost_in_credits', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vehicle_pkey')
    )
    # ### end Alembic commands ###
